### ISSUE TITLE
Tip: enable CI

### ISSUE THREAD

**Issue by hugovk** [Open-Source-Studio-at-ITP/corpora#6]
If you enable Travis CI for this repo, it'll run some basic checks on PRs and merges, like checking the JSON is valid and has no duplicate values.

**Comment by shiffman** [comment]
Oh awesome, thank you! This is exactly the topic for this week in class!

**Comment by shiffman** [comment]
Activated!

**Comment by hugovk** [comment]
Good stuff, and it's been catching stuff already :)
